[tool.poetry]
name = "inbound-client"
version = "0.0.1"
description = "Inbound Client"
authors = [ "Virksomhetsdatalaget <virksomhetsdatalaget@nav.no>", ]
readme = "README.md"
packages = [{ include = "inbound" }]

[tool.poetry.dependencies]
python = "^3.11.0"
click = "8.1.3"
pygit2 = "1.12.0"

inbound-core = { version = "0.0.1" }
inbound-gcs = { version = "0.0.1" }
inbound-sqlalchemy = { version = "0.0.1" }
inbound-snowflake = { version = "0.0.1" }

[tool.poetry.group.dev.dependencies]
inbound-core = { path="../core", develop=true }
inbound-gcs = { path="../gcs", develop=true }
inbound-sqlalchemy = { path="../sqlalchemy", develop=true }
inbound-snowflake = { path="../snowflake", develop=true }

[tool.poetry.scripts]
inbound = 'inbound.client.cli:inbound'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"