[tool.poetry]
name = "inbound-bigquery"
version = "0.0.1"
description = "Inbound BigQuery Connector"
authors = [ "Virksomhetsdatalaget <virksomhetsdatalaget@nav.no>", ]
packages = [{ include = "inbound" }]

[tool.poetry.dependencies]
python = "^3.10.0"
google-cloud-bigquery = "3.9.0"
google-auth = "2.17.3"

inbound-core = { version = "0.0.1" }

[tool.poetry.group.dev.dependencies]
inbound-core = { path="../core", develop=true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

