[tool.poetry]
name = "inbound-oracle"
version = "0.0.1"
description = "Inbound Oracle Connector"
authors = [ "Virksomhetsdatalaget <virksomhetsdatalaget@nav.no>", ]
packages = [{ include = "inbound" }]

[tool.poetry.dependencies]
python = "^3.10.0"
oracledb = "1.3.0"

inbound-core = { version = "0.0.1" }
inbound-sqlalchemy = { version = "0.0.1" }

[tool.poetry.group.dev.dependencies]
inbound-core = { path="../core", develop=true }
inbound-sqlalchemy = { path="../sqlalchemy", develop=true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

