[tool.poetry]
name = "inbound-core"
version = "0.0.1"
description = "Inbound Core"
authors = [ "Virksomhetsdatalaget <virksomhetsdatalaget@nav.no>", ]
readme = "README.md"
packages = [{ include = "inbound" }]

[tool.poetry.dependencies]
python = "^3.10.0"
pandas = ">=1.0.0,<2.1.0" # required by snowflake python connector
pyarrow = ">=10.0.1,<14.1.0" # required by snowflake python connector
loguru = "^0.7.0"
PyYAML = "^6.0"
Jinja2 = "^3.1.2"
google-cloud-secret-manager = "^2.16.2"
google-auth = "^2.23.0"
click = "^8.1.7"
pydantic = "^2.3.0"
pydantic-settings = "^2.0.3"

[tool.poetry.group.dev.dependencies]


[tool.poetry.scripts]
inbound = "inbound.core.cli:inbound"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


