[tool.poetry]
name = "inbound-sqlalchemy"
version = "0.0.1"
description = "Inbound SQLAlchemy Connector"
authors = [ "Virksomhetsdatalaget <virksomhetsdatalaget@nav.no>", ]
packages = [{ include = "inbound" }]

[tool.poetry.dependencies]
python = "^3.10.0"

inbound-core = { version = "0.0.1" }
sqlalchemy = "<2.0.0,>=1.4.0" #2.0 not supported by snowflake-sqlalchemy yet

[tool.poetry.group.dev.dependencies]
inbound-core = { path="../core", develop=true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

