version: "1.0"

# Databases
databases:
  - test_database:
      shared: no
      schemas:
        - raw
        - stages
        - marts
        - meta
        - test_schema
# Roles
roles:
  - test_role:
      warehouses:
        - test_warehouse
      privileges:
        databases:
          read:
            - test_database
          write:
            - test_database
        schemas:
          read:
            - test_database.raw
            - test_database.stages
            - test_database.marts
            - test_database.meta
            - test_database.test_schema
          write:
            - test_database.raw
            - test_database.stages
            - test_database.marts
            - test_database.meta
            - test_database.test_schema
        tables:
          read:
            - test_database.raw.*
            - test_database.stages.*
            - test_database.marts.*
            - test_database.meta.*
            - test_database.test_schema.*
          write:
            - test_database.raw.*
            - test_database.stages.*
            - test_database.marts.*
            - test_database.meta.*
            - test_database.test_schema.*
      owns:
        tables:
            - test_database.raw.*
            - test_database.stages.*
            - test_database.marts.*
            - test_database.meta.*
            - test_database.test_schema.*
      owner: useradmin

# Users
users:
  - test_user:
      can_login: yes
      member_of:
        - test_role


# Warehouses
warehouses:
  - test_warehouse:
      size: x-small


