[tool.poetry]
name = "inbound-postgres"
version = "0.0.1"
description = "Inbound PostgreSQL Connector"
authors = [ "Virksomhetsdatalaget <virksomhetsdatalaget@nav.no>", ]
packages = [{ include = "inbound" }]

[tool.poetry.dependencies]
python = "^3.11.0"
psycopg2 = "2.9.6"

inbound-core = { version = "0.0.1" }
inbound-sqlalchemy = { version = "0.0.1" }

[tool.poetry.group.dev.dependencies]
inbound-core = { path="../core", develop=true }
inbound-sqlalchemy = { path="../sqlalchemy", develop=true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

