[tool.poetry]
name = "my_project"
version = "0.0.1"
description = "my_description"
authors = [ "me <me@my.email>", ]

[tool.poetry.dependencies]
python = "^3.10.0"
inbound-core = { git = "https://github.com/navikt/inbound.git", subdirectory="packages/core" }
inbound-duckdb = {git = "https://github.com/navikt/inbound.git", subdirectory = "packages/duckdb"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
click = "^8.1.3"
black = "^23.1.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pylint = "^2.16.3"
pyright = "^1.1.296"
jupyter="1.0.0"